# Title Text
TITLE_GAME = "Asteroids"
TITLE_GAME_OVER = "GAME OVER"
TITLE_SCOREBOARD = "High Scores"
TITLE_OPTIONS = "Options"
TITLE_CREDITS = "Credits"
TITLE_SCORE = "SCORE: "
TITLE_PAUSED = "Paused"
TITLE_RESUME = "Resume"

# Menu item labels
MENU_ITEM_PLAY = "[ENTER] Play!"
MENU_ITEM_OPTIONS = "[O] Options"
MENU_ITEM_SCOREBOARD = "[S] Scoreboard"
MENU_ITEM_CREDITS = "[C] Credits"
MENU_ITEM_REPLAY = "[ENTER] Replay!"
MENU_ITEM_MAIN_MENU = "[ESC] Main Menu"

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1280

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_ACCELERATION = 600

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.3
SHOT_MAX_RANGE = 500
SHOT_SFX = "assets/720118__baggonotes__player_shoot1.wav"
