GAME_TITLE = 'Asteroids'

MAIN_MENU_PLAY = '[ENTER] Play!'
MAIN_MENU_OPTIONS = '[O] Options'
MAIN_MENU_SCOREBOARD = '[S] Scoreboard'
MAIN_MENU_CREDITS = '[C] Credits'

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 1280

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8 
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_ACCELERATION = 600

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.3
SHOT_MAX_RANGE = 500
SHOT_SFX = 'assets/720118__baggonotes__player_shoot1.wav'

GAME_OVER_TEXT = 'Game Over!'
GAME_OVER_SCORE = 'SCORE: '
GAME_OVER_REPLAY = "[ENTER] Replay!"
GAME_OVER_MAIN_MENU = '[ESC] Main Menu'
GAME_OVER_SCOREBOARD = '[S] Scoreboard'
GAME_OVER_CREDITS = '[C] Credits'

SCOREBOARD_TITLE = "High Scores"

OPTIONS_TITLE = "Options"

CREDITS_TITLE = "Credits"