ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

ENEMY_SHIP_RADIUS = 20

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
PLAYER_ACCELERATION = 600

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.25
SHOT_MAX_RANGE = 500
SHOT_SFX = "assets/720118__baggonotes__player_shoot1.wav"
